name: Generate Sitemap

# DÃ©clenchement : chaque push sur photos.js
on:
  push:
    paths:
      - 'docs/photos.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Generate sitemap
      working-directory: docs   # important ! on se place dans docs/
      run: node generate-sitemap.js

    - name: Show sitemap preview
      working-directory: docs
      run: cat sitemap.xml
