name: Generate Sitemap

on:
  push:
    paths:
      - 'docs/photos.js'   # d√©clenche seulement si photos.js change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Generate sitemap
      run: |
        cd docs
        node generate-sitemap.js

    - name: Commit sitemap
      run: |
        cd docs
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add sitemap.xml
        git commit -m "Auto-generate sitemap.xml" || echo "No changes to commit"
        git push
